generator:
  class: sfPropelGenerator
  param:
    model_class:           RcTenant
    theme:                 admin15
    non_verbose_templates: true
    with_show:             false
    singular:              RcTenant
    plural:                RcTenants
    route_prefix:          rc_tenant
    with_propel_route:     1
    actions_base_class:    sfActions

    config:
      actions: ~
      fields: 
        tenant_id: { label: Id }
      list:
        title: Tenants
        display: [ _tenant_id, _company_name, api_name, nip ]
        object_actions: {  _edit: ~ }
        batch_actions: {}
        actions: {}
      filter:  ~
      form:
        class: RcTenantAdminForm
      edit:
        title: Edit Tenant
      new:
        title: New Tenant
