# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/11-App

# default values
all:
  sf_guard_plugin:
    success_signin_url:    @homepage
    success_signout_url:   @homepage
    remember_cookie_name:  ready4cloud_admin_remember
    remember_key_expiration_age: 2592000
    check_password_callable: [ rtOpenStackAuth, checkPassword ]

  system:
    languages: [ pl, en ]

  sf_admin_dash:
    web_dir:                      /sfAdminDashPlugin
    image_dir:                    /sfAdminDashPlugin/images/icons/
    default_image:                config.png
    resize_mode:                  thumbnail
    site:                         RootBox
    include_path:                 true
    include_jquery_no_conflict:   false
    logout:                       true
    login_route:                  @sf_guard_signin
    logout_route:                 @sf_guard_signout
    items:
      'Home page':
        url: @homepage
    categories:
      Tenant:
        items:
          'Tenant list':
            url:    @rc_tenant
            image:  users.png
      Payment:
        url:    @rc_payment
        image:  generic.png
        items:
          'Payment list':
            url:    @rc_payment
            image:  generic.png
