<?php



/**
 * Skeleton subclass for representing a row from the 'rc_invoice' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.6.5-dev on:
 *
 * pią, 18 maj 2012, 20:13:40
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    propel.generator.lib.model
 */
class RcInvoice extends BaseRcInvoice
{
  public function __toString()
  {
    return $this->getSimpleName();
  }

  public function getSimpleName()
  {
    return sprintf('#%d %s - %s', $this->getInvoiceId(), $this->getIssueAt(), $this->getBuyerName());
  }

  public function getTotalNetto()
  {
    $total = 0;
    foreach($this->getRcInvoiceItems() as $it)
    {
      $total += $it->getNetto();
    }
    return $total;
  }

  public function getTotalCost()
  {
    $total = 0;
    foreach($this->getRcInvoiceItems() as $it)
    {
      $total += $it->getCost();
    }
    return $total;
  }

  public function getTotalTax()
  {
    $total = 0;
    foreach($this->getRcInvoiceItems() as $it)
    {
      $total += $it->getTax();
    }
    return $total;
  }
} // RcInvoice
