<?php



/**
 * Skeleton subclass for representing a row from the 'rc_invoice_item' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.6.5-dev on:
 *
 * pią, 18 maj 2012, 20:13:40
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    propel.generator.lib.model
 */
class RcInvoiceItem extends BaseRcInvoiceItem
{
  public function getUnitPrice()
  {
    return $this->getNetto() / $this->getQty();
  }

  public function getNetto()
  {
    return $this->getCost() - $this->getTax();
  }

  public function calcCosts()
  {
    $cost  = $this->getPrice() * $this->getQty(); 
    $rate  = (integer)$this->getTaxRate();
    $netto = $cost * 100 / (100 + $rate);
    $tax   = $cost - $netto;
    $this->setTax(sprintf('%.2f', $tax));
    $this->setCost(sprintf('%.2f', $cost));
  }
} // RcInvoiceItem
