<?php



/**
 * Skeleton subclass for representing a row from the 'rc_payment' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.6.5-dev on:
 *
 * Fri Jul 20 22:58:57 2012
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    propel.generator.lib.model
 */
class RcPayment extends BaseRcPayment
{
  public function preInsert(PropelPDO $con = null)
  {
    $this->setSessionId($this->generateSessionId());

    $tenant = RcTenantQuery::create()->findOneByApiId($this->getTenantApiId());
    $this->setRcTenant($tenant);

    $trans = new RcTransaction();
    $trans->setRcPayment($this);

    return true;
  }

  private function generateSessionId()
  {
    do {
      $session_id = md5(time());
      $payment = RcPaymentQuery::create()->findOneBySessionId($session_id);
      if(!$payment) return $session_id;
    } while(true);
  }

} // RcPayment
