<?php



/**
 * Skeleton subclass for representing a row from the 'rc_profile' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.6.5-dev on:
 *
 * nie, 20 maj 2012, 10:21:21
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    propel.generator.lib.model
 */
class RcProfile extends BaseRcProfile
{
  public function __toString()
  {
    $name = trim(sprintf('%s %s %s', $this->getTitle(), $this->getFirstName(), $this->getLastName()));
    if($name) return $name;
    return $this->getsfGuardUser()->getUsername();
  }

  public function getEmail()
  {
    return $this->getsfGuardUser()->getUsername();
  }
} // RcProfile
