<?php



/**
 * Skeleton subclass for performing query and update operations on the 'rc_promo_code' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.6.5-dev on:
 *
 * Tue Jul 10 21:16:56 2012
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    propel.generator.lib.model
 */
class RcPromoCodePeer extends BaseRcPromoCodePeer {

} // RcPromoCodePeer
