<?php



/**
 * Skeleton subclass for performing query and update operations on the 'rc_tenant' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.6.5-dev on:
 *
 * Tue Jul  3 17:54:10 2012
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    propel.generator.lib.model
 */
class RcTenantQuery extends BaseRcTenantQuery {

} // RcTenantQuery
