# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/11-App

# default values
all:
  sf_guard_plugin:
    profile_class:        RcProfile
    profile_field_name:   profile_id
  rt_payu_plugin:
    route_url:       /payment/notify
    notify_callback: [ BilingService, notify ]
  recaptcha:
    private_key:  6LffzNMSAAAAAGDlUb8oV2G4QceRErUZfXNwGc9A 
    enabled:      true
  invoice:
    seller_name:    'Radey4Cloud'
    seller_address: 'Ulica 123/456'
    seller_post:    '12-345 Miasto'
    seller_nip:     '123-456-78-90'
    seller_bank:    '00 1234 5678 9000 0000 0000 1234'
  currency:
    symbol: zł
