all:
  presets:
    default:
      host: 178.239.138.10
      port: 5000
    auth:
      host: 178.239.138.10
      port: 5000
    client:
      host: 178.239.138.10
      port: 8090
    server:
      host: 178.239.138.10
      port: 8774
    topup:
      host: 178.239.138.10
      port: 8095
  admin:
    auth_token:  VvpMBCV6x6WL087Q70wi2Lti0wkiNGoX
    tenant_name: fred
    user:        fred
    pass:        Abrakadabra.2
  topup:
    tenant_name: frontend001
    user:        frontend001
    pass:        8cfICqis2yGPC5L3

