propel:

  rc_address:
    address_id:   { type: integer, required: true, primaryKey: true, autoIncrement: true }
    street:       { type: varchar(50), required: false }
    post_code:    { type: varchar(8),  required: false }
    city:         { type: varchar(50), required: false }
    phone:        { type: varchar(25), required: false }

  rc_tenant:
    tenant_id:      { type: integer, required: true, primaryKey: true, autoIncrement: true }
    type:           { type: tinyint, required: true, default: 0 }
    company_name:   { type: varchar(99), required: false }
    nip:            { type: varchar(16), required: false }
    www:            { type: varchar(16), required: false }
    default_address_id: { type: integer, required: false, foreignTable: rc_address, foreignReference: address_id }
    invoice_address_id: { type: integer, required: false, foreignTable: rc_address, foreignReference: address_id }
    api_id:         { type: varchar(99), required: false }
    api_name:       { type: varchar(99), required: false }

  rc_profile:
    profile_id:   { type: integer, required: true, primaryKey: true, foreignTable: sf_guard_user, foreignReference: id }
    tenant_id:    { type: integer, required: false, foreignTable: rc_tenant, foreignReference: tenant_id }
    title:        { type: varchar(10), required: false }
    first_name:   { type: varchar(50), required: true }
    last_name:    { type: varchar(50), required: true }

  rc_invoice:
    invoice_id:     { type: integer, required: true, primaryKey: true, autoIncrement: true }
    profile_id:     { type: integer, required: true, foreignTable: rc_profile, foreignReference: profile_id }
    type:           { type: integer, required: true, default: 0 }
    number:         { type: integer, required: true }
    pattern:        { type: varchar(30),  required: true }
    message:        { type: varchar(30),  required: false }
    seller_name:    { type: varchar(100), required: true }
    seller_address: { type: varchar(200), required: true }
    seller_nip:     { type: varchar(16),  required: true }
    seller_bank:    { type: varchar(32),  required: true }
    buyer_name:     { type: varchar(100), required: true }
    buyer_address:  { type: varchar(200), required: true }
    buyer_nip:      { type: varchar(16),  required: false }
    created_at:     { type: timestamp, required: true }
    issue_at:       { type: date, required: true }
    sale_at:        { type: date, required: true }
    payment_date:   { type: date, required: true }
    payment_type:   { type: integer, required: true, default: 0 }

  rc_invoice_item:
    item_id:     { type: integer, required: true, primaryKey: true, autoIncrement: true }
    invoice_id:  { type: integer, required: true, foreignTable: rc_invoice, foreignReference: invoice_id }
    name:        { type: longvarchar, required: true }
    qty:         { type: integer, required: true }
    tax_rate:    { type: integer, required: true }
    price:       { type: decimal, size: 10, scale: 2, required: true }
    tax:         { type: decimal, size: 10, scale: 2, required: true }
    cost:        { type: decimal, size: 10, scale: 2, required: true }

  rc_promo_code:
    code_id:     { type: integer, required: true, primaryKey: true, autoIncrement: true }
    code:        { type: varchar(16), required: true, index: unique }
    value:       { type: decimal, size: 10, scale: 2, required: true }
    expired_at:  { type: timestamp, required: false }
    used_at:     { type: timestamp, required: false }
    used_by:     { type: integer, required: false, foreignTable: rc_tenant, foreignReference: tenant_id }
    
  rc_payment:
    payment_id:   { type: integer, required: true, primaryKey: true, foreignTable: rt_payu_transaction, foreignReference: transaction_id }
    tenant_id:    { type: integer, required: true, foreignTable: rc_tenant, foreignReference: tenant_id }
    tenant_api_id: { type: varchar(50), required: true }
    amount:       { type: integer, required: true, min: 50 }
    first_name:   { type: varchar(50), required: true }
    last_name:    { type: varchar(50), required: true }
    email:        { type: varchar(50), required: true }
    phone:        { type: varchar(25), required: false }
    invoice:      { type: boolean, required: true, default: false }
    company_name: { type: varchar(99), required: false }
    street:       { type: varchar(50), required: false }
    post_code:    { type: varchar(8),  required: false }
    city:         { type: varchar(50), required: false }
    nip:          { type: varchar(16), required: false }
    desc:         { type: varchar(255), required: false }
    client_ip:    { type: varchar(16), required: false }
    created_at:   { type: timestamp, required: true }


