<?php



/**
 * Skeleton subclass for representing a row from the 'rt_payu_transaction' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.6.5-dev on:
 *
 * Thu Jul 26 14:10:17 2012
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    propel.generator.plugins.rtPayuPlugin.lib.model
 */
class RtPayuTransaction extends BaseRtPayuTransaction
{
  public function preInsert(PropelPDO $con = null)
  {
    $this->setSessionId($this->generateSessionId());
    return true;
  }

  private function generateSessionId()
  {
    do {
      $session_id = md5(time() . mt_rand());
      $trans = RtPayuTransactionQuery::create()
        ->filterByPosId($this->getPosId())
        ->findOneBySessionId($session_id);

      if(!$trans) return $session_id;
    } while(true);
  }
} // RtPayuTransaction
