<?php



/**
 * Skeleton subclass for performing query and update operations on the 'rt_payu_transaction' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.6.5-dev on:
 *
 * Thu Jul 26 14:10:17 2012
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    propel.generator.plugins.rtPayuPlugin.lib.model
 */
class RtPayuTransactionPeer extends BaseRtPayuTransactionPeer
{
  private static $status_map = array(
    0 => 'transaction not started',
    1 => 'transaction new',
    2 => 'transaction cancelled',
    3 => 'transaction rejected',
    4 => 'transaction started',
    5 => 'transaction to receive',
    7 => 'transaction cancelled rejected',
    99 => 'transaction received',
    888 => 'incorrect status',
  );

  public static function getStatusLabel($status)
  {
    if(isset(self::$status_map[$status])) return self::$status_map[$status];
    return self::$status_map[888];
  }
} // RtPayuTransactionPeer
